version: "3.7"
services:

services:
  app:
    image: node:12
    command: node_modules/.bin/persea --dir=dist dev
    environment:
      - PORT=80
      - DB_URI=postgres://postgres@db/postgres
    depends_on:
      - db
    ports:
      - 1111:80
    working_dir: /app
    volumes:
      - ./backend:/app

  compiler:
    image: node:12
    command: node_modules/.bin/tsc --watch
    working_dir: /app
    volumes:
      - ./backend:/app

  checkups-worker:
    image: node:12
    command: node_modules/.bin/ts-node src/workers/checkups.ts
    environment:
      - DB_URI=postgres://postgres@db/postgres
      - SMTP_URI=smtp://test:password@mailhog:1025/?pool=true
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./backend:/app

  tasks-worker:
    image: node:12
    command: node_modules/.bin/ts-node src/workers/tasks.ts
    environment:
      - DB_URI=postgres://postgres@db/postgres
      - SMTP_URI=smtp://test:password@mailhog:1025/?pool=true
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./backend:/app

  test-service:
    image: node:12
    command: node_modules/.bin/persea --port=80 run
    working_dir: /app
    volumes:
      - ./examples/test-service:/app

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1113:8025

  db:
    image: postgres
