version: "3.7"
services:

services:
  app:
    image: node:12
    command: node_modules/.bin/persea --require=ts-node/register --dir=src dev
    environment:
      - PORT=80
      - DB_URI=postgres://postgres@db/postgres
    depends_on:
      - db
    ports:
      - 1111:80
    working_dir: /app
    volumes:
      - ./backend:/app

  worker:
    image: node:12
    command: node_modules/.bin/ts-node src/worker.ts
    environment:
      - DB_URI=postgres://postgres@db/postgres
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./backend:/app

  db:
    image: postgres
